### ISSUE TITLE
the unique dream id problem

### ISSUE THREAD

**Issue by sir1st** [Ixaruz/Luna#1]
really interesting work, but after i download the dreams using my own town as a template, it's ok for internet connection( i can get and use the dodo code), but the dream id is still showed the map interface and any operations about change my own dream will failed for the reason 'internet connection error', do you have any tips or information for that? Thanks very much.

**Comment by Ixaruz** [comment]
I didn't do enough research on that yet. I will try to look into it in the future.

**Comment by Ixaruz** [comment]
Could you add me on discord so I can work with you on this problem? Poyo#0030

**Comment by sir1st** [comment]
sir1st#9823, friend request already sent on discord
