### ISSUE TITLE
Wrong Save File Revision Error

### ISSUE THREAD

**Issue by OnlyAtRisk** [Ixaruz/Luna#2]
I put my own save file as a template instead of the one provided and I am getting this error. How do I fix?

**Comment by Ixaruz** [comment]
Either you forgot to decrypt the save (the save revision error should show seemingly "random" digits) or you have to actually update the save/template ingame to either version 1.11.0 or 1.11.1.

Best wishes :)

**Comment by OnlyAtRisk** [comment]
I did forget to decrypt my save file. Thanks for the fix :). Great Program!
